apps/b3_user_panel/urls.py
from django.conf.urls import url
import apps.b3_user_panel.views as views
from apps.b3_user_panel.verification_views import \
    user_addresses_pending_verifications_view, \
    user_addresses_pending_verifications_update_view

urlpatterns = [
    url((r'projects/(?P<project_id>[0-9]+)/lines/'
         '(?P<line_id>[0-9]+)/u/(?P<uuid>[a-f0-9\-]+)'),
        views.project_line_viewer, name='project-line-viewer'),
    url(r'^projects/(?P<project_id>[0-9]+)/order/$',
        views.order_basket,
        name='order-project'),

    url(r'^projects/(?P<project_id>[0-9]+)/',
        views.project_detail_view,
        name='project-detail'),

    url(r'^projects/$',
        views.projects_view,
        name='projects'),

    url(r'^project-quotation/(?P<project_id>[0-9]+)/$',
        views.project_detail_view_quotation,
        name='project-quotation'),

    # ---- Below urls used for setting new address models in old UP ----
    url(
        r'^settings/user-address/$',
        views.user_address_view,
        name='user-address'),
    url(
        r'^settings/user-address/edit/(?P<pk>[0-9]+)/$',
        views.NewUserAddressSettingsUpdateView.as_view(),
        name='edit-user-address'),
    url(
        r'^settings/user-address/delete/(?P<user_address_id>[0-9]+)/$',
        views.delete_user_address_view,
        name='delete-user-address'),

    # --------------------------------------------------------------------
    url(r'^settings/', views.settings_view, name='settings'),

    url(r'^pending-verifications/$',
        user_addresses_pending_verifications_view,
        name='pending-verifications'),
    url(r'^pending-verifications/update/$',
        user_addresses_pending_verifications_update_view,
        name='pending-verifications-update'),
]

button3d/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from django.views.generic.base import RedirectView
from django.views.i18n import javascript_catalog
from filebrowser.sites import site

import apps.b3_compare.api_v1_views as v1
from apps.b3_checkout.views.payment_redirect_target_user_panel import \
    payment_redirect_target_view
from apps.b3_compare import views as compare_views
from apps.b3_core import views, ajax_views
from apps.b3_manual_request import views as manual_request_views
from apps.b3_misc import views as views_pages
from apps.b3_organization import admin_views
from apps.b3_signup.forms import CustomSetPasswordForm, ResetPasswordForm
from apps.b3_signup.views import (
    LoginView, extended_registration_verification_pending_view,
    EmailSignupView, EmailSignupSetPasswordView, EmailSignupConfirmView,
    popup_success, EmailSignupExtendedRegistrationView,
    extended_registration_addresses_view,
    extended_registration_addresses_delete_view,
    PrintingServiceWelcomeView, PrintingServiceWelcomeConfirmView
)
from apps.b3_user_panel.views import change_password

admin.autodiscover()

js_info_dict = {
    'packages': ('pages',
                 'uploads',)
}

handler500 = 'apps.b3_core.views.handler500'


urlpatterns = [
    url(r'^u/(?P<uuid>[a-f0-9\-]+)/$',
        lambda request, uuid: redirect('short_uploads_views:upload',
                                       uuid=uuid),
        name='short_uploads'),
    # Auth Plugins
    url(
        r'^auth/',
        include('apps.b3_auth_plugins.urls', namespace="b3_auth_plugins")
    ),
    url(
        r'^api-auth/', include(
            'rest_framework.urls', namespace='rest_framework'
        )
    ),
    url(
        r'^api/v2.0/', include(
            'apps.b3_api.urls', namespace="api_urls"
        )
    ),
]

uploads_patterns = [
    url(r'^(?P<uuid>[a-f0-9\-]+)/$',
        compare_views.compare, name='upload'),

    # Ajax callbacks
    url(r'^(?P<uuid>[a-f0-9\-]+)/generic_upload/$',
        compare_views.generic_upload, name='generic_upload'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_optimized/$',
        compare_views.download_optimized, name='download_optimized'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_original/$',
        compare_views.download_original, name='download_original'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_thumbnail/$',
        compare_views.download_thumbnail, name='download_thumbnail'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_wta/$',
        compare_views.download_wta, name='download_wta'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_support/$',
        compare_views.download_support, name='download_support'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_viewer_original/$',
        compare_views.download_viewer_original,
        name='download_viewer_original'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_viewer_optimized/$',
        compare_views.download_viewer_optimized,
        name='download_viewer_optimized'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_texture_original/$',
        compare_views.download_texture_original,
        name='download_texture_original'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_texture_optimized/$',
        compare_views.download_texture_optimized,
        name='download_texture_optimized'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_viewer_simple/$',
        compare_views.download_viewer_simple, name='download_viewer_simple'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_repaired_simple/$',
        compare_views.download_repaired_simple,
        name='download_repaired_simple'),

    # Workaround for Sketchup for Mac.
    # Sketchup will open this url because of some wired CLRF ist appended
    url(r'^(?P<uuid>[a-f0-9\-]+)/\r\n\r\n/$',
        RedirectView.as_view(pattern_name='upload',
                             permanent=False)),  # %0D%0A%0D%0A
]

urlpatterns += i18n_patterns(
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^imprint/',
        RedirectView.as_view(url='https://www.3yourmind.com', permanent=False),
        name='imprint'),
    url(r'^jobs/',
        RedirectView.as_view(url='https://www.3yourmind.com', permanent=False),
        name='jobs'),
    url(r'^terms/',
        RedirectView.as_view(url='https://www.3yourmind.com', permanent=False),
        name='terms'),
    url(r'^contact/',
        RedirectView.as_view(url='https://www.3yourmind.com', permanent=False),
        name='contact'),
    url(r'^uploads/', include(uploads_patterns)),
    url(r'^u/', include(uploads_patterns, namespace='short_uploads_views')),

    # demo
    url(r'^demo/$',
        compare_views.compare,
        name='demo'),

    # misc
    url(r'^error/(?P<error>[a-z0-9\-]+)', views_pages.error, name='error'),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^i18n/', include('django.conf.urls.i18n')),


    # Override admin login/logout
    url(r'^admin/login/', admin_views.login, name='login'),
    url(r'^admin/logout/', admin_views.logout, name='logout'),

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # Status Page
    url(r'^status/', include('apps.status_page.urls')),

    # Allauth
    url(r'^accounts/login/$',
        LoginView.as_view(), name='account_login'),
    url(r'^accounts/logout/$',
        auth_views.logout, {'next_page': 'home'}, name='account_logout'),
    url(r'^accounts/signup/$',
        EmailSignupView.as_view(),
        name='account_email_signup'),
    url(r'^accounts/signup/confirm/(?P<key>\w+)/?$',
        EmailSignupConfirmView.as_view(),
        name='account_email_signup_confirm'),
    url(r'^accounts/signup/set-password/$',
        EmailSignupSetPasswordView.as_view(),
        name='account_email_signup_set_password'),
    url(r'^accounts/signup/extended-registration/$',
        EmailSignupExtendedRegistrationView.as_view(),
        name='account_email_extended_registration'),
    url(r'^accounts/signup/extended-registration-addresses/$',
        extended_registration_addresses_view,
        name='account_email_extended_registration_addresses'),
    url((r'^accounts/signup/extended-registration-addresses'
         '/delete/(?P<user_address_id>[0-9]+)/$'),
        extended_registration_addresses_delete_view,
        name='account_email_extended_registration_addresses_delete'),
    url(r'^accounts/popup-success/$',
        popup_success, name='account_popup_success'),
    url(r'^accounts/password/change/$',
        change_password, name='account_change_password'),
    url(r'^accounts/password/reset/$',
        auth_views.password_reset,
        {'template_name': "account/password_reset.html",
         'password_reset_form': ResetPasswordForm},
        name='account_reset_password'),
    url(r'^accounts/password/reset/done/$',
        auth_views.password_reset_done,
        {'template_name': "account/password_reset_done.html"},
        name='password_reset_done'),
    url((r'^accounts/password/reset/key/'
         '(?P<uidb64>[0-9A-Za-z]+)/(?P<token>.+)/$'),
        auth_views.password_reset_confirm,
        {'template_name': "account/password_reset_from_key.html",
         'set_password_form': CustomSetPasswordForm},
        name='account_reset_password_from_key'),
    url(r'^accounts/password/reset/key/done/$',
        auth_views.password_reset_complete,
        {'template_name': "account/password_reset_from_key_done.html"},
        name='password_reset_complete'),
    url(r'^accounts/verification-pending/$',
        extended_registration_verification_pending_view,
        name='verification_pending'),
    # Printing Service onboarding
    url(r'^accounts/ps_signup/$',
        EmailSignupView.as_view(),
        {"is_ps": True},
        name='account_ps_email_signup'),
    url(r'^accounts/ps_welcome/$',
        PrintingServiceWelcomeView.as_view(),
        name='account_ps_welcome'),
    url(r'^accounts/ps_welcome_confirm/$',
        PrintingServiceWelcomeConfirmView.as_view(),
        name='account_ps_welcome_confirm'),

    # User Panel
    url(r'^user/',
        include('apps.b3_user_panel.urls', namespace="b3_user_panel")),

    # Dashboard - Pro accounts
    url(r'^dashboard/',
        include('apps.b3_organization.urls',
                namespace="b3_organization")),


    # Manual requests
    url(r'^request/$',
        manual_request_views.manual_request,
        name='manual-request'),
    url(r'^request/attachment/ajax$',
        manual_request_views.ManualRequestAtachmentAjaxView.as_view(),
        name='manual-request-attachments'),

    # Used in several places to get all countries
    url(r'^all-countries-ajax/',
        views.get_all_countries_view, name='all-countries-ajax'),
)

urlpatterns += [
    url(r'^admin/filebrowser/',
        include(site.urls)),
    url(r'^grappelli/',
        include('grappelli.urls')),
    url(r'^ckeditor/',
        include('ckeditor_uploader.urls')),
    url(r'^compatibility/$',
        compare_views.upload_file, name='upload-file'),

    # Basket ajax calls
    url(r'^basket-ajax/',
        include('apps.basket.urls', namespace='basket-ajax')),
    url(r'^change_site_configuration/',
        ajax_views.change_site_configuration,
        name='change_site_configuration'),

    # NETS Payment callback redirection target
    url(r'^payment-redirect-target/',
        payment_redirect_target_view, name='payment-redirect-target')
]

# api v1
urlpatterns += [
    url(r'^v1/uploads/(?P<uuid>[a-f0-9\-]+)/$',
        v1.UploadView.as_view(), name='v1_uploads_uuid'),
    url(r'^v1/material-prices/$',
        v1.materials.MaterialPricesView.as_view(),
        name='v1_material_prices'
        ),
    url(r'^v1/supplier-prices/$',
        v1.suppliers.SupplierPricesView.as_view(),
        name='v1_supplier_prices'
        ),

apps/b3_api/services/offers/post_processings/views/base.py
from django.http import Http404

from apps.b3_api.errors.api_responses import error_object_not_found
from apps.b3_api.services.offers.views import BaseStockRecordView
from apps.partner.models import PostProcessing


class BasePostProcessingView(BaseStockRecordView):
    def get_object(self):
        try:
            return PostProcessing.objects.get(
                id=self.kwargs['post_processing_id'],
                stock_record_id=self.kwargs['offer_id'],
                stock_record__partner_id=self.kwargs['service_id'],
            )
        except PostProcessing.DoesNotExist:
            raise Http404(
                error_object_not_found(
                    object_name='PostProcessing',
                    object_id=self.kwargs['post_processing_id']
                )
            )

apps/b3_api/users/views/base.py
from django.contrib.auth.models import User
from rest_framework.generics import get_object_or_404
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView


class UserBaseView(APIView):
    permission_classes = (
        IsAuthenticated,
    )

    def get_object(self):
        return get_object_or_404(User, id=self.request.user.id)

apps/b3_user_panel/views/order_user_panel_detail.py
from django.http import Http404
from rest_framework.generics import RetrieveAPIView
from rest_framework.permissions import IsAuthenticated

from apps.b3_api.errors.api_responses import error_object_not_found
from apps.b3_order.models import Order
from apps.b3_user_panel.serializers.order_user_panel_detail_serializer \
    import OrderUserPanelDetailSerializer


class OrderUserPanelDetail(RetrieveAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = OrderUserPanelDetailSerializer
    lookup_url_kwarg = 'order_id'

    def get_order(self) -> Order:
        try:
            return Order.objects.get(
                id=self.kwargs['order_id'], purchased_by=self.request.user
            )
        except Order.DoesNotExist:
            raise Http404(
                error_object_not_found(
                    object_name='ORDER', object_id=self.kwargs['order_id']
                )
            )

    def get_object(self) -> Order:
        return self.get_order()

apps/b3_user_panel/views/order_user_panel_list.py
import operator
import typing as t
from decimal import Decimal, DecimalException
from functools import reduce

from django.db import models
from django_filters import rest_framework as filters
from rest_framework.compat import distinct
from rest_framework.filters import SearchFilter
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.settings import api_settings

import button3d.type_declarations as td
from apps.b3_api.mixins import PaginatedViewMixin
from apps.b3_order.models import Order
from apps.b3_user_panel.serializers.order_user_panel_list_serializer \
    import OrderUserPanelListSerializer


class OrderFilter(filters.FilterSet):
    datetime_placed = filters.DateFromToRangeFilter()
    status = filters.CharFilter(field_name='current_status__type')
    partner_name = filters.CharFilter(field_name='partner__name')

    class Meta:
        model = Order
        fields = ['partner_name', 'datetime_placed', 'status']


def convert_decimal(candidate: str) -> t.Optional[Decimal]:
    try:
        return Decimal(candidate)
    except DecimalException:
        return None


class OrderListSearchBackend(SearchFilter):
    def filter_queryset(self,
                        request: td.HttpRequest,
                        queryset: td.DjangoQuerySet,
                        view: td.DjangoView):
        """
        If search terms are convertable to a numeric value, then we also
        filter on order total (both excl. and incl. matches)
        """
        search_fields = getattr(view, 'search_fields', None)
        search_terms = self.get_search_terms(request)

        if not search_fields or not search_terms:
            return queryset

        orm_lookups = [
            self.construct_search(str(search_field))
            for search_field in search_fields
        ]

        base = queryset
        conditions = []
        add_total_incl_tax = False
        for search_term in search_terms:
            queries = [
                models.Q(**{orm_lookup: search_term})
                for orm_lookup in orm_lookups
            ]
            number = convert_decimal(search_term)
            if number is not None:
                add_total_incl_tax = True
                queries.append(
                    models.Q(total_value=number) |
                    models.Q(total_incl_tax=number)
                )

            conditions.append(reduce(operator.or_, queries))

        if add_total_incl_tax:
            queryset = queryset.annotate(
                total_incl_tax=models.F('total_value') + models.F('total_tax')
            )
        queryset = queryset.filter(reduce(operator.and_, conditions))
        if self.must_call_distinct(queryset, search_fields):
            # Filtering against a many-to-many field requires us to
            # call queryset.distinct() in order to avoid duplicate items
            # in the resulting queryset.
            # We try to avoid this if possible, for performance reasons.
            queryset = distinct(queryset, base)

        return queryset


class OrderUserPanelList(PaginatedViewMixin, ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = OrderUserPanelListSerializer
    filter_class = OrderFilter
    filter_backends = api_settings.DEFAULT_FILTER_BACKENDS + [
        OrderListSearchBackend
    ]
    search_fields = (
        'number',
        'customer_reference',
        'partner__name',
    )
    ordering_field_mapping = {
        'status': 'current_status__type',
    }
    ordering_fields = (
        'status',
        'total_value',
        'datetime_placed',
        'customer_reference',
        'number',
    )

    def get_queryset(self) -> td.DjangoQuerySet:
        return Order.objects.filter(purchased_by=self.request.user)

apps/b3_user_panel/templates/b3_user_panel/ajax_pagination.html
{% load staticfiles %}

<div class="b3-spinner hidden">
    <div class="loading-content">
        <img src="{% static "images/spinner.gif" %}">
    </div>
</div>

{% if not knockout %}
<nav class="paginator">
    {% if paging.visible %}
        <div class="text-right">
            <ul class="pagination">
                <li>
                    <a onclick="loadData('{{ paging.first_url }}'); return false" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% for page_url in paging.range_urls %}
                    <li {% if page_url.is_current %}class="active"{% endif %}>
                        <a onclick="loadData('{{ page_url.url }}'); return false" href="#">{{ page_url.title }}</a>
                    </li>
                {% endfor %}
                <li>
                    <a onclick="loadData('{{ paging.last_url }}'); return false" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </div>
    {% endif %}
</nav>

<script type="text/javascript">

    function loadData(page){
        $('.b3-data').hide();
        $('.b3-spinner').removeClass('hidden');
        $('.paginator').hide();
        $('.ajax_refresh_area').load(page+' .ajax_refresh_area', function() {
            $('.b3-spinner').addClass('hidden');
            $('.paginator').show();
        });
    }

</script>
{% else %}
<script type="text/javascript">
    function showSpinner(){
        $('.b3-spinner').removeClass('hidden');
    }
    function hideSpinner(timeout){
        if (typeof timeout == "undefined") {
            timeout = 1000;
        }
        setTimeout(function(){ $('.b3-spinner').addClass('hidden'); }, timeout);
    }
</script>
{% endif %}

apps/b3_user_panel/templates/b3_user_panel/base.html
{% extends "b3_core/base.html" %}
{% load i18n %}
{% load l10n %}
{% load compress %}
{% load staticfiles %}
{% block title %}{{ stl_file.showname }}{% endblock %}
{% block class %}uploads{% endblock %}
{% block og_title %}<meta property="og:title" content="{% trans '3YOURMIND ' %}{{ stl_file.showname }}"/>{% endblock %}
{% block og_description %}<meta property="og:description" content="{% trans '3D Model on 3YOURMIND ' %}:{{ stl_file.showname }}"/>{% endblock %}
{% block og_video %}{% endblock %}
{% block content %}
    {% compress js %}
    <script src="{% static "js/button3d/common/beautify.js" %}"></script>
    <script src="{% static "js/button3d/userpanel/StringPolyfill.js" %}"></script>
    {% endcompress %}
    <script>
        var djangoData = (function () {
            var requestUserEmail = '{{ request.user.email }}';
            var noOwner = '{{ basket.owner }}' == 'None';

            var requestUser = {
                email: requestUserEmail
            };

            return {
                requestUser: requestUser,
                basketNoOwner: noOwner
            };
        })();

        var projectData = (function () {
            var projectId = null;
            {% if basket %}
                projectId = parseInt('{{ basket.id }}');
            {% endif %}
            return {
                id: projectId,
            }
        })();

        function getUserId() {
            var userId = null;
            {% if request.user.is_authenticated %}
                userId = parseInt('{{ request.user.id }}');
            {% endif %}
            return userId;
        }
    </script>
    <div id="detail-wrapper">
    {% if request.user.is_authenticated %}
        {% include "b3_user_panel/usernav.html" %}
    {% endif %}
    {% block submenu %}{% endblock %}
    <div class="container b3-container-stretch">
        {% block user_content %}{% endblock %}
    </div>
    </div>
{% endblock %}

apps/b3_user_panel/templates/b3_user_panel/calendar.html
{% comment %}TODO ugly hardcoded translations for calendar{% endcomment %}
<script type="text/javascript">
    {% if LANGUAGE_CODE == 'de'%}
        $('.date-picker').daterangepicker(
    {
        startDate: moment(),
        endDate:  moment(),
        ranges: {
               'Heute': [moment(), moment()],
               'Gestern': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
               'Letzte 7 Tage': [moment().subtract(6, 'days'), moment()],
               'Letzte 30 Tage': [moment().subtract(29, 'days'), moment()],
               'Dieser Monat': [moment().startOf('month'), moment().endOf('month')],
               'Letzter Monat': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        locale: {
            "format": "DD.MM.YYYY",
            "separator": " - ",
            "applyLabel": "Wählen",
            "cancelLabel": "Abbrechen",
            "fromLabel": "Von",
            "toLabel": "Bis",
            "customRangeLabel": "Custom",
            "weekLabel": "W",
            "daysOfWeek": [
                "So",
                "Mo",
                "Di",
                "Mi",
                "Do",
                "Fr",
                "Sa"
            ],
            "monthNames": [
                "Januar",
                "Februar",
                "März",
                "April",
                "Mai",
                "Juni",
                "Juli",
                "August",
                "September",
                "Oktober",
                "November",
                "Dezember"
            ],
            "firstDay": 1
        },
        applyClass: "btn-default"
    });

    {% else %}

    $('.date-picker').daterangepicker(
    {
        startDate: moment(),
        endDate:  moment(),
        ranges: {
               'Today': [moment(), moment()],
               'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
               'Last 7 Days': [moment().subtract(6, 'days'), moment()],
               'Last 30 Days': [moment().subtract(29, 'days'), moment()],
               'This Month': [moment().startOf('month'), moment().endOf('month')],
               'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        locale: {
            "format": "MM/DD/YYYY",
            "separator": " - ",
            "applyLabel": "Apply",
            "cancelLabel": "Cancel",
            "fromLabel": "From",
            "toLabel": "To",
            "customRangeLabel": "Custom",
            "weekLabel": "W",
            "daysOfWeek": [
                "Su",
                "Mo",
                "Tu",
                "We",
                "Th",
                "Fr",
                "Sa"
            ],
            "monthNames": [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December"
            ],
            "firstDay": 1
        },
        applyClass: "btn-default"
    });
    {% endif %}

    setTimeout(function() {
        $('.clear-btn').trigger('click');
    }, 0);
</script>

apps/b3_user_panel/templates/b3_user_panel/user_addresses_pending_verifications.html
{% extends "b3_user_panel/base.html" %}
{% load i18n %}
{% load l10n %}
{% load staticfiles %}
{% load currency_tags %}
{% load b3_utils %}

{% block title %}{% trans "Pending verifications" %}{% endblock %}

{% block user_content %}
<style>
.pending-buttons-view,
.verified-buttons-view,
.declined-buttons-view{
    display: none
}
.address-container.pending .pending-buttons-view,
.address-container.verified .verified-buttons-view,
.address-container.declined .declined-buttons-view{
    display: inline-block;
}
</style>
<div class="ajax_refresh_area" xmlns:address="http://www.w3.org/1999/xhtml">
    <div class="b3-make-space"></div>
    <div class="row">
        <span>Filter by: </span>
        <a class="btn btn-default" href="?filter_verified_status=pending">{% trans "Pending" %}</a>
        <a class="btn btn-default" href="?filter_verified_status=declined">{% trans "Declined" %}</a>
        <a class="btn btn-default" href="?filter_verified_status=verified">{% trans "Verified" %}</a>
    </div>
    <div class="b3-make-space"></div>
    {% if user_addresses %}
        {% for address in user_addresses %}
            <div class="row address-container {{ address.verified_status }}">
                <div class="well">
                  {% block select_address_fields %}

                  <p class="b3-address-name">{% if address.title %}{{address.title}} {% endif %}{{address.first_name}} {{ address.last_name}}</p>
                      <p>{{ address.user.email }}</p><br />
                      <b>{% trans "Company Name" %}: </b>{{address.company_name}} <br/>
                      <b>{% trans "Department" %}: </b>{{address.department}} <br/>
                      <b>{{ organization.vat_id_label }}:</b> {{ address.vat_id }}<br/>
                      <br />
                      <b>{% trans "Address" %}</b>
                      <br />
                    {{address.line1}}<br/>
                    {% if address.line2 %}{{address.line2}}<br/>{% endif %}
                  {{address.zip_code}} {{ address.city }}{% if address.state %}, {{address.state}}{% endif %}<br />
                    {{address.country}}<br/>
                      <br>
                      <b>{% trans "Phone" %}: </b>{{address.phone_number}} <br/>
                  </p>

                  {% endblock %}
                </div>



                <div class="pending-buttons-view">
                    <span>Status: Pending</span>
                    <button class="btn btn-default" data-id="{{ address.id }}" data-new-status="verified" onclick="update_verify_address(this)">{% trans "Verify" %}</button>
                    <button class="btn btn-default" data-id="{{ address.id }}" data-new-status="declined" onclick="update_verify_address(this)">{% trans "Decline" %}</button>
                </div>
                <div class="verified-buttons-view">
                    <span>Status: Verified</span>
                    <button class="btn btn-default" data-id="{{ address.id }}" data-new-status="declined" onclick="update_verify_address(this)">{% trans "Decline" %}</button>
                </div>
                <div class="declined-buttons-view">
                    <span>Status: Declined</span>
                    <button class="btn btn-default" data-id="{{ address.id }}" data-new-status="verified" onclick="update_verify_address(this)">{% trans "Verify" %}</button>
                </div>
            </div>
            <div class="b3-make-space"></div>
        {% endfor %}
        {% include "b3_user_panel/ajax_pagination.html" with knockout=False %}
        <div class="b3-make-space"></div>
        <div class="b3-make-space"></div>
        <script>
            function update_verify_address(elem){
                var id = $(elem).data("id");
                var new_status = $(elem).data("new-status");
                $.post("{% url 'b3_user_panel:pending-verifications-update' %}",
                    {"id":id,"new_status":new_status},
                    function(data){
                        if(data.success){
                            $($(elem).parents(".address-container")[0]).removeClass("pending verified declined").addClass(data.new_status);
                        }
                    })
            }
        </script>
    {% else %}
        <div class="text-center">
            <h1>{% trans "No addresses to list." %}</h1>
            <p>
                {% trans "As soon as customer will register, add or change his address it will appear as pending." %}
            </p>
        </div>
    {% endif %}
</div>

{% endblock %}