apps/b3_organization/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'$', views.dashboard, name='dashboard'),
]

apps/b3_user_panel/urls.py
from django.conf.urls import url
import apps.b3_user_panel.views as views
from apps.b3_user_panel.verification_views import \
    user_addresses_pending_verifications_view, \
    user_addresses_pending_verifications_update_view

urlpatterns = [
    url((r'projects/(?P<project_id>[0-9]+)/lines/'
         '(?P<line_id>[0-9]+)/u/(?P<uuid>[a-f0-9\-]+)'),
        views.project_line_viewer, name='project-line-viewer'),
    url(r'^projects/(?P<project_id>[0-9]+)/order/$',
        views.order_basket,
        name='order-project'),

    url(r'^projects/(?P<project_id>[0-9]+)/',
        views.project_detail_view,
        name='project-detail'),

    url(r'^projects/$',
        views.projects_view,
        name='projects'),

    url(r'^project-quotation/(?P<project_id>[0-9]+)/$',
        views.project_detail_view_quotation,
        name='project-quotation'),

    # ---- Below urls used for setting new address models in old UP ----
    url(
        r'^settings/user-address/$',
        views.user_address_view,
        name='user-address'),
    url(
        r'^settings/user-address/edit/(?P<pk>[0-9]+)/$',
        views.NewUserAddressSettingsUpdateView.as_view(),
        name='edit-user-address'),
    url(
        r'^settings/user-address/delete/(?P<user_address_id>[0-9]+)/$',
        views.delete_user_address_view,
        name='delete-user-address'),

    # --------------------------------------------------------------------
    url(r'^settings/', views.settings_view, name='settings'),

    url(r'^pending-verifications/$',
        user_addresses_pending_verifications_view,
        name='pending-verifications'),
    url(r'^pending-verifications/update/$',
        user_addresses_pending_verifications_update_view,
        name='pending-verifications-update'),
]

button3d/urls.py
                 'uploads',)
}

handler500 = 'apps.b3_core.views.handler500'


urlpatterns = [
    url(r'^u/(?P<uuid>[a-f0-9\-]+)/$',
        lambda request, uuid: redirect('short_uploads_views:upload',
                                       uuid=uuid),
        name='short_uploads'),
    # Auth Plugins
    url(
        r'^auth/',
        include('apps.b3_auth_plugins.urls', namespace="b3_auth_plugins")
    ),
    url(
        r'^api-auth/', include(
            'rest_framework.urls', namespace='rest_framework'
        )
    ),
    url(
        r'^api/v2.0/', include(
            'apps.b3_api.urls', namespace="api_urls"
        )
    ),
]

uploads_patterns = [
    url(r'^(?P<uuid>[a-f0-9\-]+)/$',
        compare_views.compare, name='upload'),

    # Ajax callbacks
    url(r'^(?P<uuid>[a-f0-9\-]+)/generic_upload/$',
        compare_views.generic_upload, name='generic_upload'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_optimized/$',
        compare_views.download_optimized, name='download_optimized'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_original/$',
        compare_views.download_original, name='download_original'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_thumbnail/$',
        compare_views.download_thumbnail, name='download_thumbnail'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_wta/$',
        compare_views.download_wta, name='download_wta'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_support/$',
        compare_views.download_support, name='download_support'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_viewer_original/$',
        compare_views.download_viewer_original,
        name='download_viewer_original'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_viewer_optimized/$',
        compare_views.download_viewer_optimized,
        name='download_viewer_optimized'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_texture_original/$',
        compare_views.download_texture_original,
        name='download_texture_original'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_texture_optimized/$',
        compare_views.download_texture_optimized,
        name='download_texture_optimized'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_viewer_simple/$',
        compare_views.download_viewer_simple, name='download_viewer_simple'),
    url(r'^(?P<uuid>[a-f0-9\-]+)/download_repaired_simple/$',
        compare_views.download_repaired_simple,
        name='download_repaired_simple'),

    # Workaround for Sketchup for Mac.
    # Sketchup will open this url because of some wired CLRF ist appended
    url(r'^(?P<uuid>[a-f0-9\-]+)/\r\n\r\n/$',
        RedirectView.as_view(pattern_name='upload',
                             permanent=False)),  # %0D%0A%0D%0A
]

urlpatterns += i18n_patterns(
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^imprint/',
        RedirectView.as_view(url='https://www.3yourmind.com', permanent=False),
        name='imprint'),
    url(r'^jobs/',
        RedirectView.as_view(url='https://www.3yourmind.com', permanent=False),
        name='jobs'),
    url(r'^terms/',
        RedirectView.as_view(url='https://www.3yourmind.com', permanent=False),
        name='terms'),
    url(r'^contact/',
        RedirectView.as_view(url='https://www.3yourmind.com', permanent=False),
        name='contact'),
    url(r'^uploads/', include(uploads_patterns)),
    url(r'^u/', include(uploads_patterns, namespace='short_uploads_views')),

    # demo
    url(r'^demo/$',
        compare_views.compare,
        name='demo'),

    # misc
    url(r'^error/(?P<error>[a-z0-9\-]+)', views_pages.error, name='error'),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^i18n/', include('django.conf.urls.i18n')),


    # Override admin login/logout
    url(r'^admin/login/', admin_views.login, name='login'),
    url(r'^admin/logout/', admin_views.logout, name='logout'),

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # Status Page
    url(r'^status/', include('apps.status_page.urls')),

    # Allauth
    url(r'^accounts/login/$',
        LoginView.as_view(), name='account_login'),
    url(r'^accounts/logout/$',
        auth_views.logout, {'next_page': 'home'}, name='account_logout'),
    url(r'^accounts/signup/$',
        EmailSignupView.as_view(),
        name='account_email_signup'),
    url(r'^accounts/signup/confirm/(?P<key>\w+)/?$',
        EmailSignupConfirmView.as_view(),
        name='account_email_signup_confirm'),
    url(r'^accounts/signup/set-password/$',
        EmailSignupSetPasswordView.as_view(),
        name='account_email_signup_set_password'),
    url(r'^accounts/signup/extended-registration/$',
        EmailSignupExtendedRegistrationView.as_view(),
        name='account_email_extended_registration'),
    url(r'^accounts/signup/extended-registration-addresses/$',
        extended_registration_addresses_view,
        name='account_email_extended_registration_addresses'),
    url((r'^accounts/signup/extended-registration-addresses'
         '/delete/(?P<user_address_id>[0-9]+)/$'),
        extended_registration_addresses_delete_view,
        name='account_email_extended_registration_addresses_delete'),
    url(r'^accounts/popup-success/$',
        popup_success, name='account_popup_success'),
    url(r'^accounts/password/change/$',
        change_password, name='account_change_password'),
    url(r'^accounts/password/reset/$',
        auth_views.password_reset,
        {'template_name': "account/password_reset.html",
         'password_reset_form': ResetPasswordForm},
        name='account_reset_password'),
    url(r'^accounts/password/reset/done/$',
        auth_views.password_reset_done,
        {'template_name': "account/password_reset_done.html"},
        name='password_reset_done'),
    url((r'^accounts/password/reset/key/'
         '(?P<uidb64>[0-9A-Za-z]+)/(?P<token>.+)/$'),
        auth_views.password_reset_confirm,
        {'template_name': "account/password_reset_from_key.html",
         'set_password_form': CustomSetPasswordForm},
        name='account_reset_password_from_key'),
    url(r'^accounts/password/reset/key/done/$',
        auth_views.password_reset_complete,
        {'template_name': "account/password_reset_from_key_done.html"},
        name='password_reset_complete'),
    url(r'^accounts/verification-pending/$',
        extended_registration_verification_pending_view,
        name='verification_pending'),
    # Printing Service onboarding
    url(r'^accounts/ps_signup/$',
        EmailSignupView.as_view(),
        {"is_ps": True},
        name='account_ps_email_signup'),
    url(r'^accounts/ps_welcome/$',
        PrintingServiceWelcomeView.as_view(),
        name='account_ps_welcome'),
    url(r'^accounts/ps_welcome_confirm/$',
        PrintingServiceWelcomeConfirmView.as_view(),
        name='account_ps_welcome_confirm'),

    # User Panel
    url(r'^user/',
        include('apps.b3_user_panel.urls', namespace="b3_user_panel")),

    # Dashboard - Pro accounts
    url(r'^dashboard/',
        include('apps.b3_organization.urls',
                namespace="b3_organization")),


    # Manual requests
    url(r'^request/$',
        manual_request_views.manual_request,
        name='manual-request'),
    url(r'^request/attachment/ajax$',
        manual_request_views.ManualRequestAtachmentAjaxView.as_view(),
        name='manual-request-attachments'),

    # Used in several places to get all countries
    url(r'^all-countries-ajax/',
        views.get_all_countries_view, name='all-countries-ajax'),
)

urlpatterns += [
    url(r'^admin/filebrowser/',
        include(site.urls)),
    url(r'^grappelli/',
        include('grappelli.urls')),
    url(r'^ckeditor/',
        include('ckeditor_uploader.urls')),
    url(r'^compatibility/$',
        compare_views.upload_file, name='upload-file'),

    # Basket ajax calls
    url(r'^basket-ajax/',
        include('apps.basket.urls', namespace='basket-ajax')),
    url(r'^change_site_configuration/',
        ajax_views.change_site_configuration,
        name='change_site_configuration'),

    # NETS Payment callback redirection target
    url(r'^payment-redirect-target/',
        payment_redirect_target_view, name='payment-redirect-target')
]

# api v1
urlpatterns += [
    url(r'^v1/uploads/(?P<uuid>[a-f0-9\-]+)/$',
        v1.UploadView.as_view(), name='v1_uploads_uuid'),
    url(r'^v1/material-prices/$',
        v1.materials.MaterialPricesView.as_view(),
        name='v1_material_prices'
        ),
    url(r'^v1/supplier-prices/$',
        v1.suppliers.SupplierPricesView.as_view(),
        name='v1_supplier_prices'
        ),
    url(r'^v1/finishes-prices/$',
        v1.finishes.FinishesPricesView.as_view(),
        name='v1_finishes_prices'
        ),
    url(r'^v1/colors/$',
        v1.ColorsView.as_view(), name='v1_colors'),
    url(r'^v1/suppliers/$',
        v1.suppliers.SuppliersView.as_view(), name='v1_suppliers'),
    url(r'^v1/materials/$',
        v1.materials.MaterialsView.as_view(), name='v1_materials'),
    url(r'^v1/finishes/$',
        v1.finishes.FinishesView.as_view(), name='v1_finishes'),
    url(r'^v1/add-to-basket/$',
        v1.add_to_basket_view, name='v1_add_to_basket'),
    url(r'^v1/custom-price/$',
        v1.get_custom_price_view, name='v1_custom_price'),
]

# Always throws exception
urlpatterns += [
    url(r'^exception/$',
        views.exception_view, name='exception'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    urlpatterns += [
        url(r'^impersonate/',
            include('apps.b3_impersonate.urls',
                    namespace='impersonate')),
    ]

    if settings.ENABLE_DEBUG_TOOL and not settings.ENABLE_SQL_DEBUG:
        import debug_toolbar
        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

    if settings.ENABLE_PROXY:
        # Activate Backend/Yoda proxy in development mode
        from button3d.proxy import proxy_patterns

apps/b3_organization/forms/options.py
from django import forms

from apps.b3_organization.models import OrganizationPartnerOption, \
    OrganizationProductOption


class OrganizationOptionForm(forms.ModelForm):
    key = forms.ChoiceField(label="Key", choices=(),
                            widget=forms.Select(attrs={'class': 'selector'}))

    def __init__(self, *args, **kwargs):
        super(OrganizationOptionForm, self).__init__(*args, **kwargs)
        self.fields['key'].choices = self._key_choices

    def _key_choices(self):
        raise NotImplementedError()


class OrganizationPartnerOptionForm(OrganizationOptionForm):
    non_required_fields = [
        'bluebox_preview_step_en',
        'bluebox_preview_step_de',
        'bluebox_preview_step']
    key_is_excluded = False

    # Excluded partner option keys. No need to move it to project settings.
    _excluded_options = (
        'id',
        'code',
        'name',
        'shortname',
        'website',
        'email',
        'price_currency',
        'site',
        'address'
    )

    def _key_choices(self):
        # To prevent circular import, import Partner here
        from apps.partner.models import Partner
        choices = []
        fields = Partner._meta.fields
        for field in fields:
            if field.name in self._excluded_options:
                continue
            choices.append(
                (field.name,
                 "{} ({})".format(
                     field.verbose_name,
                     field.name)))
        return choices

    def is_valid(self):
        valid = super(OrganizationPartnerOptionForm, self).is_valid()
        if 'key' not in self.cleaned_data or \
                'site' not in self.cleaned_data or \
                'partners' not in self.cleaned_data:
            return False
        if not valid:
            key = str(self.cleaned_data['key'])
            value = self.cleaned_data['value'] \
                if 'value' in self.cleaned_data else None

            # Check fields that can have empty values with actual value
            if key in self.non_required_fields:
                self.key_is_excluded = True

            if self.key_is_excluded and not value:
                return True
        return valid

    """
    Overriding whole save method to be able to set instance.value
        as None avoiding to catch self.errors of validation
    """

    def save(self, commit=True):

        if self.errors:
            if 'value' in self.errors and self.key_is_excluded:
                self.instance.value = ""
            else:
                raise ValueError(
                    ("The %s could not be %s because "
                     "the data didn't validate.") %
                    (self.instance._meta.object_name,
                     'created' if self.instance._state.adding else 'changed',
                     ))
        if commit:
            self.instance.save()
            self._save_m2m()
        else:
            self.save_m2m = self._save_m2m
        return self.instance

    class Meta:
        model = OrganizationPartnerOption
        fields = '__all__'


class OrganizationProductOptionForm(OrganizationOptionForm):
    _excluded_options = (
        'id',
        'site',
        'parent',
        'date_created',
        'date_updated',
        'slug',
        'technology',
        'product_class',
        'is_discountable',
        'upc',
    )

    class Meta:
        model = OrganizationProductOption
        fields = '__all__'

    def _key_choices(self):
        from apps.catalogue.models.product import Product
        choices = []
        fields = Product._meta.fields
        for field in fields:
            if field.name in self._excluded_options:
                continue
            choices.append(
                (field.name, "{} ({})".format(field.verbose_name, field.name)))
        return choices

apps/b3_organization/views.py
from django.shortcuts import render

from apps.b3_core.utils import determine_default_currency
from apps.b3_user_panel.permissions import check_user_permission
from apps.basket.models import Basket
from apps.b3_order.models import Order


@check_user_permission
def dashboard(request):
    orders = Order.objects.filter(
        purchased_by=request.user).order_by('-datetime_placed')[:3]
    template = 'b3_organization/dashboard.html'
    context = {
        'current_currency': determine_default_currency(request),
        'orders': orders
    }

    baskets, _ = Basket.search(owner=request.user, items_per_page=3)
    context['projects'] = [{
        'id': b.id,
        'title': b.title,
        'date': b.date_created,
        'lines': b.lines.all()[:2],  # Display two thumbnails
        'total_lines': b.num_lines
    } for b in baskets]

    return render(request, template, context)

apps/b3_organization/templates/b3_organization/dashboard.html
{% extends "b3_user_panel/base.html" %}
{% load i18n %}
{% load l10n %}
{% load staticfiles %}
{% load compress %}
{% load b3_utils %}
{% load organization_flags %}
{% load currency_tags %}

{% block title %}{% trans "Dashboard" %}{% endblock %}
{% block class %}dashboard{% endblock %}

{% block user_content %}

<div class="b3-make-space"></div>

<div class="row">
    <div class="col-sm-12 col-md-{% if organization.key_manager %}8{% else %}12{% endif%}">
        <div class="panel short-bottom">
            <div class="panel-heading link-right">
                <h4>{% blocktrans %}Recent 3D Projects{% endblocktrans %}</h4>
                {% if projects|length > 0 %}<a href="{% url 'b3_user_panel:projects' %}">{% blocktrans %}See all 3D Projects{% endblocktrans %}</a>{% endif %}
            </div>
            <div class="panel-body">
                <div class="row">
                    {% if  projects %}
                        {% for project in projects %}
                        <div class="col-sm-12 col-md-4">
                            <a href="{% url 'b3_user_panel:project-detail' project.id %}" style="color: inherit;" >
                                <div class="panel no-margin-bottom b3-list-uploads-panel b3-data">
                                    <div class="panel-body" style="padding-bottom: 0">
                                        <div class="arrow-no-text b3-heading-title no-margin-bottom" style="display:inline-block;cursor:pointer;" title="{{ project.title }}" {% if project.title|length > 20 %} data-toggle="tooltip" {% endif %}>{% if project.title|length > 20 %}{{ project.title|inline_truncate:20 }}{% else %}{{ project.title }}{% endif %}</div>
                                        <div class="text-right" style="display:inline-block;float: right;margin-top: -5px;font-size: 18px;"><i style="display:none;" class="fa fa-close"></i></div>
                                        <div class="row" style="cursor:pointer;margin-bottom:15px;margin-top:15px;min-height:52px;">
                                            {% for line in project.lines %}
                                                <div class="col-xs-6"
                                                     style="{% if forloop.counter0 == 0 %}padding-right: 0px;margin-left: -6px;{% endif %} {% if forloop.counter0 == 1 %}padding-left: 0px;margin-left: 6px;{% endif %}">
                                                    <img draggable="false"  class="img-thumbnail" src="{{ line.thumbnail_url }}"
                                                     onerror="svgFallback(this)"
                                                     alt="3YOURMIND">
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-6">
                                                <p class="arrow-no-text" style="cursor:pointer !important;" >{{ project.date |date:"SHORT_DATE_FORMAT" }}</p>
                                            </div>
                                            <div class="col-xs-6" style="padding-left: 0;">
                                                <p class="arrow-no-text" style="float: right;cursor:pointer !important; " >
                                                    {% if project.total_lines == 0 %}{% trans 'Empty' %}{% endif %}
                                                    {% if project.total_lines == 1 %}{% trans '1 file' %}{% endif %}
                                                    {% if project.total_lines > 1 %}{{ project.total_lines }} {% trans 'files' %}{% endif %}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        {% endfor %}
                    {% else %}

                        <div class="text-center">
                            <h4>{% trans "You haven't created any 3D projects so far." %}</h4>
                            <p>
                                {% trans "Start a new 3D project" %}
                            </p>
                            <div class="btn" style="width:40%;" onclick="Button3d.modals.show_new_project_modal()" href="">{% trans "New 3D project" %}</div>
                        </div>

                    {% endif %}
                </div>

            </div>
        </div>
        {% if not use_new_user_panel %}
        <div class="panel short-bottom">
            <div class="panel-heading link-right">
                <h4>{% blocktrans %}Recent Orders{% endblocktrans %}</h4>
            </div>
            <div class="panel-body table-responsive">

                {% if orders %}
                    <table class="table no-margin-bottom table-bordered table-striped">
                        <thead>
                            <tr class="active">
                                <th>{% trans 'Order Number' %}</th>
                                <th>{% trans 'Name - Shipping Address' %}</th>
                                <th>{% trans 'Order Date' %}</th>
                                <th>{% trans 'Total' %}</th>
                                <th>{% trans 'Paid' %}</th>
                                <th>{% trans 'Order State' %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                                <tr style="height: 55px;">
                                    <td><a href="{{ order.basket.url }}">{{ order.number }}</a></td>
                                    <td>
                                        {% if order.shipping_address %}
                                            {{ order.shipping_address }}
                                        {% elif order.pickup_location %}
                                            {{ order.pickup_location }}
                                        {% endif %}
                                    </td>
                                    <td>{{ order.datetime_placed|date:"SHORT_DATE_FORMAT" }}</td>
                                    <td>{{ order.total.incl_tax|currency:order.currency }}</td>
                                    <td>{{ order.payment.payment_method.name }}</td>
                                    <td>{% trans order.status.type %}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div class="text-center">
                        <h4>{% trans "You haven't ordered anything." %}</h4>
                        <p>
                            {% trans "As soon as you place an order, it will appear here." %}
                        </p>
                    </div>
                {% endif %}

            </div>
        </div>
        {% endif %}
    </div>

    {% if organization.key_manager %}
    <div class="col-sm-12 col-md-4">
        {% with organization.key_manager as key_manager %}
            <div class="panel short-bottom">
                <div class="panel-heading">
                    <h4>{{ key_manager.title }}</h4>
                </div>
                <div class="panel-body">
                    <div class="row" style="margin-bottom:15px;">
                        {% if key_manager.manager_photo %}
                            <div class="col-xs-4">
                                <img draggable="false" class="img-thumbnail" src="{{ key_manager.manager_photo.url }}">
                            </div>
                        {% endif %}
                        <div class="col-xs-8">
                            <p class="b3-heading-title">{{ key_manager.name }}</p>
                            <p>{{ key_manager.role }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="b3-heading-title line">{% trans 'Contact' %}</div>
                        </div>
                        <div class="col-xs-12" style="margin-bottom:10px;">
                            <div class="row">
                                <div class="col-xs-4 b3-text-gray text-left">{% trans 'Email' %}:</div>
                                <div class="col-xs-8 text-left"><a href="mailto:{{ key_manager.email }}">{{ key_manager.email }}</a></div>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-4 b3-text-gray text-left">{% trans 'Telephone' %}:</div>
                                <div class="col-xs-8 text-left">{{ key_manager.telephone }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endwith %}
    </div>
    {% endif %}
</div>

<div class="b3-make-space"></div>

<script>
    $('[data-toggle="tooltip"]').tooltip();
</script>

{% endblock %}